import {
  Building2,
  Car,
  CandlestickChart,
  Code,
  Coins,
  Cpu,
  Flag,
  Fuel,
  HeartPulse,
  Landmark,
  Lightbulb,
  Newspaper,
  Plane,
  Shield,
  Shirt,
  Store,
  TrendingUp,
  UtensilsCrossed,
  Wallet,
  Bike,
  type LucideIcon,
} from "lucide-react"

export const categoryIcons: Record<string, LucideIcon> = {
  bancos: Building2,
  fintechs: Wallet,
  crypto: Coins,
  tecnologias: Cpu,
  alycs: TrendingUp,
  acciones: CandlestickChart,
  "entes-estatales": Landmark,
  prepagas: HeartPulse,
  retail: Store,
  medios: Newspaper,
  automotrices: Car,
  alimentos: UtensilsCrossed,
  combustibles: Fuel,
  seguros: Shield,
  indumentaria: Shirt,
  gastronomia: Bike,
  turismo: Plane,
  energia: Lightbulb,
  "indie-projects": Code,
  banderas: Flag,
}

export function getCategoryIcon(categoryId: string): LucideIcon | null {
  return categoryIcons[categoryId] ?? null
}
