export interface Entity {
  id: number
  name: string
  domain: string
}

export interface Category {
  id: string
  name: string
  description: string
  seoTopEntities: [string, string, string]
  seoIntro: string
  entities: Entity[]
}

export const categories: Category[] = [
  {
    id: "bancos",
    name: "Bancos",
    description: "Bancos tradicionales y públicos de Argentina",
    seoTopEntities: ["Banco Nación", "Banco Galicia", "BBVA"],
    seoIntro:
      "Logos oficiales de bancos argentinos en PNG y SVG transparente. Banco Nación, Galicia, BBVA, Santander, Macro, Provincia y 10 entidades más. Descarga gratis los logos de los principales bancos tradicionales y públicos de Argentina para diseño, presentaciones y proyectos.",
    entities: [
      { id: 1, name: "Banco de la Nación Argentina", domain: "bna.com.ar" },
      { id: 2, name: "Banco Santander Río", domain: "santander.com.ar" },
      { id: 3, name: "BBVA Argentina", domain: "bbva.com.ar" },
      { id: 4, name: "Banco Galicia", domain: "www.galicia.ar" },
      { id: 5, name: "Banco Macro", domain: "macro.com.ar" },
      { id: 6, name: "Banco Provincia (Bs. As.)", domain: "bancoprovincia.com.ar" },
      { id: 7, name: "Banco Ciudad", domain: "bancociudad.com.ar" },
      { id: 8, name: "Banco Patagonia", domain: "bancopatagonia.com.ar" },
      { id: 9, name: "Banco Hipotecario", domain: "hipotecario.com.ar" },
      { id: 10, name: "Banco Supervielle", domain: "www.supervielle.com.ar" },
      { id: 13, name: "Banco Comafi", domain: "www.comafi.com.ar" },
      { id: 16, name: "Banco Piano", domain: "www.bancopiano.com.ar" },
      { id: 17, name: "Banco de Córdoba (BANCOR)", domain: "bancor.com.ar" },
      { id: 18, name: "BPN (Banco Provincia de Neuquén)", domain: "www.bpn.com.ar" },
      { id: 23, name: "Naranja X", domain: "naranjax.com" },
      { id: 24, name: "Brubank", domain: "brubank.com" },
      { id: 33, name: "Uilo Bank (ex Wilobank)", domain: "uilo.com.ar" },
      { id: 346, name: "Banco Credicoop", domain: "credicoop.coop" },
      { id: 349, name: "Banco de Corrientes", domain: "www.bancodecorrientes.com.ar" },
      { id: 350, name: "Banco de La Pampa", domain: "bancodelapampa.com.ar" },
    ],
  },
  {
    id: "fintechs",
    name: "Fintechs",
    description: "Billeteras digitales, neobancos y apps financieras",
    seoTopEntities: ["Ualá", "Mercado Pago", "Lemon Cash"],
    seoIntro:
      "Logos de fintechs, billeteras digitales y neobancos en Argentina en PNG y SVG. Ualá, Mercado Pago, Lemon Cash, Prex, Personal Pay, MODO, Belo y 19 entidades más. Descarga gratis los logos de las principales apps financieras de Argentina.",
    entities: [
      { id: 21, name: "Ualá", domain: "uala.com.ar" },
      { id: 22, name: "Mercado Pago", domain: "mercadopago.com.ar" },
      { id: 25, name: "Belo", domain: "belo.app" },
      { id: 26, name: "Lemon Cash", domain: "lemon.me" },
      { id: 27, name: "Personal Pay", domain: "www.personal.com.ar" },
      { id: 28, name: "Prex", domain: "prex.com.ar" },
      { id: 29, name: "ARQ", domain: "www.arqfinance.com" },
      { id: 30, name: "Fiwind", domain: "fiwind.io" },
      { id: 31, name: "Ripio", domain: "ripio.com" },
      { id: 32, name: "Buenbit", domain: "buenbit.com" },
      { id: 34, name: "Carrefour Banco", domain: "www.bancodeserviciosfinancieros.com.ar" },
      { id: 38, name: "Claro Pay", domain: "claropay.com.ar" },
      { id: 39, name: "Astropay", domain: "astropay.com" },
      { id: 63, name: "MODO", domain: "www.modo.com.ar" },
      { id: 64, name: "Binance", domain: "binance.com" },
      { id: 66, name: "Nexo", domain: "nexo.com" },
      { id: 67, name: "OKX", domain: "okx.com" },
      { id: 68, name: "Kraken", domain: "kraken.com" },
      { id: 69, name: "Coinbase", domain: "coinbase.com" },
      { id: 70, name: "Roxom", domain: "roxom.com" },
      { id: 71, name: "Berry", domain: "berryinvesting.com" },
      { id: 72, name: "Wise", domain: "wise.com" },
      { id: 74, name: "Payoneer", domain: "payoneer.com" },
      { id: 75, name: "Pomelo", domain: "pomelo.la" },
      { id: 76, name: "Tapi", domain: "tapi.la" },
    ],
  },
  {
    id: "alycs",
    name: "ALyCs",
    description: "Agentes de Liquidación y Compensación (brokers)",
    seoTopEntities: ["Balanz", "IOL", "PPI"],
    seoIntro:
      "Logos de ALyCs y brokers de bolsa argentina en PNG y SVG. Balanz, InvertirOnline, PPI, Allaria, Bull Market, Cohen y 3 más. Descarga gratis los logos de los principales agentes de liquidación.",
    entities: [
      { id: 41, name: "Invertir Online (IOL)", domain: "invertironline.com" },
      { id: 42, name: "Balanz", domain: "balanz.com" },
      { id: 43, name: "Allaria", domain: "allaria.com.ar" },
      { id: 44, name: "Bull Market Brokers", domain: "bullmarketbrokers.com" },
      { id: 45, name: "PPI", domain: "www.portfoliopersonal.com" },
      { id: 46, name: "IEB (Invertir en Bolsa)", domain: "www.iebmas.com.ar" },
      { id: 47, name: "Cohen Aliados", domain: "cohen.com.ar" },
      { id: 49, name: "SBS Trading", domain: "www.gruposbs.com" },
      { id: 37, name: "Cocos", domain: "cocos.capital" },
      { id: 360, name: "Veta Capital", domain: "vetacap.com.ar" },
    ],
  },
  {
    id: "acciones",
    name: "Acciones",
    description: "Empresas listadas en la Bolsa argentina",
    seoTopEntities: ["YPF", "Galicia", "BBVA"],
    seoIntro:
      "Logos de empresas listadas en la Bolsa argentina en PNG y SVG. YPF, Galicia, BBVA, Macro, BYMA, Aluar y 13 más. Descarga gratis los logos de las principales acciones del mercado local.",
    entities: [
      { id: 363, name: "Aluar", domain: "www.aluar.com.ar" },
      { id: 364, name: "YPF", domain: "ypf.com" },
      { id: 365, name: "BBVA", domain: "bbva.com.ar" },
      { id: 366, name: "Macro", domain: "macro.com.ar" },
      { id: 367, name: "BYMA", domain: "www.byma.com.ar" },
      { id: 368, name: "Central Puerto", domain: "www.centralpuerto.com" },
      { id: 369, name: "Cresud", domain: "www.cresud.com.ar" },
      { id: 370, name: "Edenor", domain: "edenor.com" },
      { id: 371, name: "Galicia", domain: "www.galicia.ar" },
      { id: 372, name: "Loma Negra", domain: "www.lomanegra.com" },
      { id: 373, name: "Metrogas", domain: "metrogas.com.ar" },
      { id: 374, name: "Pampa", domain: "pampa.com" },
      { id: 375, name: "Supervielle", domain: "www.supervielle.com.ar" },
      { id: 376, name: "Transener", domain: "www.transener.com.ar" },
      { id: 377, name: "Ternium", domain: "ar.ternium.com" },
      { id: 378, name: "Banco de Valores", domain: "www.valo.ar" },
      { id: 379, name: "A3 Mercados", domain: "a3mercados.com.ar" },
      { id: 380, name: "Banco Patagonia", domain: "bancopatagonia.com.ar" },
      { id: 381, name: "Celulosa Argentina", domain: "www.celulosaargentina.com.ar" },
    ],
  },
  {
    id: "entes-estatales",
    name: "Entes estatales",
    description: "Organismos públicos con servicios fiscales y tributarios",
    seoTopEntities: ["ARCA", "BCRA", "AGIP"],
    seoIntro:
      "Logos de organismos públicos y entes estatales argentinos en PNG y SVG. ARCA (ex AFIP), BCRA y AGIP. Descarga gratis los logos de los principales organismos fiscales y de regulación.",
    entities: [
      { id: 61, name: "ARCA (ex AFIP)", domain: "www.afip.gob.ar" },
      { id: 62, name: "AGIP", domain: "www.agip.gob.ar" },
      { id: 65, name: "BCRA", domain: "bcra.gob.ar" },
    ],
  },
  {
    id: "retail",
    name: "Retail",
    description: "Comercios y cadenas de consumo masivo en Argentina",
    seoTopEntities: ["Mercado Libre", "Coto", "Frávega"],
    seoIntro:
      "Logos de cadenas de retail argentinas en PNG y SVG. Mercado Libre, Coto, Frávega, Jumbo, Disco y 10 comercios más. Descarga gratis los logos de las principales marcas de consumo masivo de Argentina.",
    entities: [
      { id: 81, name: "Mercado Libre", domain: "mercadolibre.com.ar" },
      { id: 82, name: "Carrefour", domain: "carrefour.com.ar" },
      { id: 83, name: "Frávega", domain: "fravega.com" },
      { id: 84, name: "Coto", domain: "coto.com.ar" },
      { id: 85, name: "Jumbo", domain: "jumbo.com.ar" },
      { id: 86, name: "Disco", domain: "disco.com.ar" },
      { id: 87, name: "Vea", domain: "vea.com.ar" },
      { id: 88, name: "La Anónima", domain: "laanonima.com.ar" },
      { id: 89, name: "Supermercados DIA", domain: "supermercadosdia.com.ar" },
      { id: 91, name: "Makro", domain: "makro.com.ar" },
      { id: 92, name: "Farmacity", domain: "farmacity.com.ar" },
      { id: 93, name: "Easy", domain: "easy.com.ar" },
      { id: 94, name: "ChangoMas", domain: "changomas.com.ar" },
      { id: 95, name: "Garbarino", domain: "garbarino.com" },
    ],
  },
  {
    id: "medios",
    name: "Medios",
    description: "Medios periodísticos y portales de noticias de Argentina",
    seoTopEntities: ["Infobae", "La Nación", "Clarín"],
    seoIntro:
      "Logos de medios y portales de noticias argentinos en PNG y SVG. Infobae, La Nación, Clarín, TN, El Cronista y 10 medios más. Descarga gratis los logos de los principales medios de comunicación de Argentina.",
    entities: [
      { id: 101, name: "Infobae", domain: "infobae.com" },
      { id: 102, name: "La Nación", domain: "lanacion.com.ar" },
      { id: 103, name: "TN (Todo Noticias)", domain: "tn.com.ar" },
      { id: 104, name: "Clarín", domain: "clarin.com" },
      { id: 105, name: "El Cronista", domain: "cronista.com" },
      { id: 106, name: "Página/12", domain: "pagina12.com.ar" },
      { id: 107, name: "Perfil", domain: "perfil.com" },
      { id: 108, name: "Ámbito Financiero", domain: "ambito.com" },
      { id: 109, name: "El Destape", domain: "www.eldestapeweb.com" },
      { id: 110, name: "La Voz del Interior", domain: "lavoz.com.ar" },
      { id: 111, name: "La Gaceta (Tucumán)", domain: "lagaceta.com.ar" },
      { id: 112, name: "Diario UNO", domain: "diariouno.com.ar" },
      { id: 113, name: "Crónica", domain: "cronica.com.ar" },
      { id: 114, name: "Los Andes (Mendoza)", domain: "losandes.com.ar" },
      { id: 115, name: "La Capital", domain: "www.lacapital.com.ar" },
      { id: 336, name: "C5N", domain: "c5n.com" },
      { id: 337, name: "A24", domain: "a24.com" },
      { id: 338, name: "Telefe", domain: "telefe.com" },
      { id: 339, name: "El Trece", domain: "eltrece.com" },
      { id: 340, name: "América TV", domain: "americatv.com.ar" },
      { id: 341, name: "Canal 26", domain: "canal26.com" },
      { id: 342, name: "La Prensa", domain: "laprensa.com.ar" },
      { id: 343, name: "El Día (La Plata)", domain: "eldia.com" },
      { id: 344, name: "Río Negro", domain: "rionegro.com.ar" },
    ],
  },
  {
    id: "automotrices",
    name: "Automotrices",
    description: "Marcas automotrices con presencia en Argentina",
    seoTopEntities: ["Toyota", "Volkswagen", "Ford"],
    seoIntro:
      "Logos de marcas automotrices en Argentina en PNG y SVG transparente. Toyota, Volkswagen, Ford, Chevrolet, Renault, Fiat y 12 marcas más. Descarga gratis los logos de las principales marcas de autos con presencia en Argentina.",
    entities: [
      { id: 121, name: "Toyota", domain: "toyota.com.ar" },
      { id: 122, name: "Volkswagen", domain: "volkswagen.com.ar" },
      { id: 123, name: "Fiat", domain: "fiat.com.ar" },
      { id: 124, name: "Renault", domain: "renault.com.ar" },
      { id: 125, name: "Peugeot", domain: "peugeot.com.ar" },
      { id: 126, name: "Ford", domain: "ford.com.ar" },
      { id: 127, name: "Chevrolet", domain: "chevrolet.com.ar" },
      { id: 128, name: "Citroën", domain: "citroen.com.ar" },
      { id: 129, name: "Jeep", domain: "jeep.com.ar" },
      { id: 130, name: "Nissan", domain: "nissan.com.ar" },
      { id: 131, name: "Hyundai", domain: "hyundai.com.ar" },
      { id: 133, name: "Kia", domain: "www.kia.com.ar" },
      { id: 134, name: "Chery", domain: "chery.com.ar" },
      { id: 135, name: "BYD", domain: "www.byd.com" },
      { id: 136, name: "Suzuki", domain: "suzuki.com.ar" },
      { id: 359, name: "Yamaha", domain: "www.yamaha-motor.com.ar" },
      { id: 137, name: "Mercedes-Benz", domain: "mercedes-benz.com.ar" },
      { id: 138, name: "BMW", domain: "bmw.com.ar" },
      { id: 139, name: "Audi", domain: "audi.com.ar" },
      { id: 351, name: "Honda", domain: "honda.com.ar" },
      { id: 352, name: "Porsche", domain: "porsche.com" },
      { id: 353, name: "Ram", domain: "www.ram.com.ar" },
      { id: 354, name: "Land Rover", domain: "www.landroverargentina.com" },
      { id: 355, name: "Dodge", domain: "www.dodge.com.ar" },
      { id: 356, name: "Subaru", domain: "subaru.com.ar" },
      { id: 358, name: "Changan", domain: "changan.com.ar" },
    ],
  },
  {
    id: "alimentos",
    name: "Alimentos y bebidas",
    description: "Empresas de alimentos y bebidas en Argentina",
    seoTopEntities: ["Arcor", "La Serenísima", "Quilmes"],
    seoIntro:
      "Logos de empresas de alimentos y bebidas argentinas en PNG y SVG. Arcor, La Serenísima, Quilmes, Nestlé, Bimbo y 7 marcas más. Descarga gratis los logos de las principales empresas de alimentos de Argentina.",
    entities: [
      { id: 141, name: "Arcor", domain: "arcor.com" },
      { id: 142, name: "Molinos Río de la Plata", domain: "molinos.com.ar" },
      { id: 143, name: "La Serenísima (Mastellone)", domain: "laserenisima.com.ar" },
      { id: 146, name: "Nestlé", domain: "nestle.com.ar" },
      { id: 147, name: "Unilever", domain: "unilever.com.ar" },
      { id: 148, name: "Mondelez", domain: "mondelezinternational.com" },
      { id: 149, name: "Bimbo", domain: "www.bimbo.com.ar" },
      { id: 152, name: "Cervecería Quilmes", domain: "quilmes.com.ar" },
      { id: 153, name: "Havanna", domain: "www.tienda.havanna.com.ar" },
      { id: 155, name: "Molino Cañuelas", domain: "molinocanuelas.com" },
      { id: 156, name: "Ledesma", domain: "ledesma.com.ar" },
      { id: 157, name: "Cervecería Patagonia", domain: "www.cervezapatagonia.com.ar" },
      { id: 310, name: "Coca-Cola (Femsa)", domain: "coca-colafemsa.com" },
      { id: 311, name: "PepsiCo", domain: "www.pepsi.es" },
      { id: 312, name: "Heineken", domain: "heineken.com.ar" },
      { id: 313, name: "Stella Artois", domain: "stellartois.com" },
      { id: 314, name: "Cerveza Corona", domain: "www.cervezacorona.com.ar" },
      { id: 315, name: "Brahma", domain: "brahma.com.ar" },
      { id: 319, name: "Paladini", domain: "paladini.com.ar" },
      { id: 361, name: "Tregar", domain: "www.tregar.com.ar" },
      { id: 362, name: "Beaudroit", domain: "familiabeaudroit.com.ar" },
    ],
  },
  {
    id: "combustibles",
    name: "Combustibles",
    description: "Empresas de combustibles y estaciones de servicio",
    seoTopEntities: ["YPF", "Shell", "AXION"],
    seoIntro:
      "Logos de empresas de combustibles y estaciones de servicio en Argentina en PNG y SVG. YPF, Shell, AXION, Puma, Gulf y 2 más. Descarga gratis los logos de las principales marcas de combustibles.",
    entities: [
      { id: 161, name: "YPF", domain: "ypf.com" },
      { id: 162, name: "Shell", domain: "shell.com.ar" },
      { id: 163, name: "AXION energy", domain: "axionenergy.com" },
      { id: 164, name: "Esso", domain: "esso.com" },
      { id: 165, name: "Gulf", domain: "gulfcombustibles.com" },
      { id: 166, name: "Puma Energy", domain: "pumaenergyarg.com.ar" },
      { id: 167, name: "Oil Combustibles", domain: "oilcombustibles.com" },
    ],
  },
  {
    id: "seguros",
    name: "Seguros",
    description: "Compañías de seguros con operación en Argentina",
    seoTopEntities: ["San Cristóbal", "Mapfre", "Allianz"],
    seoIntro:
      "Logos de compañías de seguros en Argentina en PNG y SVG. San Cristóbal, Mapfre, Allianz, La Caja, Provincia Seguros y 3 más. Descarga gratis los logos de las principales aseguradoras del país.",
    entities: [
      { id: 171, name: "Federación Patronal Seguros", domain: "fedpat.com.ar" },
      { id: 172, name: "Sancor Seguros", domain: "sancorseguros.com.ar" },
      { id: 173, name: "La Segunda Seguros", domain: "www.lasegunda.com.ar" },
      { id: 174, name: "San Cristóbal Seguros", domain: "sancristobal.com.ar" },
      { id: 175, name: "La Caja Seguros", domain: "lacaja.com.ar" },
      { id: 176, name: "Mapfre", domain: "mapfre.com.ar" },
      { id: 177, name: "Allianz", domain: "www.allianz.com.ar" },
      { id: 178, name: "Provincia Seguros", domain: "provinciaseguros.com.ar" },
    ],
  },
  {
    id: "indumentaria",
    name: "Indumentaria",
    description: "Marcas y cadenas de indumentaria en Argentina",
    seoTopEntities: ["Rapsodia", "Cheeky", "Grimoldi"],
    seoIntro:
      "Logos de marcas y cadenas de indumentaria argentina en PNG y SVG. Rapsodia, Cheeky, Grimoldi, Maria Cher, Mimo, Markova. Descarga gratis los logos de las principales marcas de moda de Argentina.",
    entities: [
      { id: 181, name: "Rapsodia", domain: "rapsodia.com.ar" },
      { id: 182, name: "Grimoldi", domain: "grimoldi.com" },
      { id: 183, name: "Cheeky", domain: "cheeky.com.ar" },
      { id: 184, name: "Mimo", domain: "mimo.com.ar" },
      { id: 186, name: "Markova", domain: "markova.com" },
      { id: 187, name: "Maria Cher", domain: "maria-cher.com.ar" },
      { id: 330, name: "Zara", domain: "zara.com" },
      { id: 331, name: "Nike", domain: "nike.com.ar" },
      { id: 332, name: "Adidas", domain: "adidas.com.ar" },
      { id: 333, name: "Puma", domain: "puma.com" },
      { id: 334, name: "Lacoste", domain: "lacoste.com" },
      { id: 335, name: "Tommy Hilfiger", domain: "ar.tommy.com" },
    ],
  },
  {
    id: "gastronomia",
    name: "Gastronomía",
    description: "Apps y marcas gastronómicas",
    seoTopEntities: ["PedidosYa", "Rappi", "Burger King"],
    seoIntro:
      "Logos de apps y marcas gastronómicas en Argentina en PNG y SVG. PedidosYa, Rappi, Burger King, McDonald's, Starbucks, Mostaza y 5 marcas más. Descarga gratis los logos de las principales cadenas de comida y delivery.",
    entities: [
      { id: 191, name: "PedidosYa", domain: "pedidosya.com.ar" },
      { id: 192, name: "Rappi", domain: "rappi.com.ar" },
      { id: 193, name: "Uber Eats", domain: "ubereats.com" },
      { id: 194, name: "Morfy", domain: "www.morfy.app" },
      { id: 195, name: "McDonald's", domain: "www.mcdonalds.com.ar" },
      { id: 196, name: "Mostaza", domain: "www.mostazaweb.com.ar" },
      { id: 197, name: "Burger King", domain: "www.burgerking.com.ar" },
      { id: 198, name: "El Club de la Milanesa", domain: "elclubdelamilanesa.com" },
      { id: 199, name: "Almacén de Pizzas", domain: "almacendepizzas.com" },
      { id: 200, name: "Starbucks", domain: "www.starbucks.com.ar" },
      { id: 216, name: "Café Martínez", domain: "www.cafemartinez.com" },
    ],
  },
  {
    id: "turismo",
    name: "Turismo",
    description: "Hotelería, viajes y paquetes turísticos",
    seoTopEntities: ["Despegar", "Aerolíneas Argentinas", "Booking"],
    seoIntro:
      "Logos de empresas de turismo, aerolíneas y hoteles en Argentina en PNG y SVG. Despegar, Aerolíneas Argentinas, Booking, Airbnb, Flybondi y 9 marcas más. Descarga gratis los logos de las principales empresas de viajes.",
    entities: [
      { id: 201, name: "Aerolíneas Argentinas", domain: "aerolineas.com.ar" },
      { id: 202, name: "Flybondi", domain: "flybondi.com" },
      { id: 203, name: "JetSMART", domain: "jetsmart.com" },
      { id: 204, name: "LATAM", domain: "latam.com" },
      { id: 205, name: "Despegar", domain: "despegar.com.ar" },
      { id: 206, name: "Almundo", domain: "almundo.com.ar" },
      { id: 207, name: "Booking.com", domain: "booking.com" },
      { id: 208, name: "Airbnb", domain: "airbnb.com.ar" },
      { id: 209, name: "Hilton", domain: "hilton.com" },
      { id: 210, name: "Accor (Ibis, Novotel, etc.)", domain: "all.accor.com" },
      { id: 211, name: "Wyndham / Howard Johnson", domain: "wyndhamhotels.com" },
      { id: 212, name: "Hertz", domain: "hertz.com.ar" },
      { id: 213, name: "Avis", domain: "avis.com.ar" },
      { id: 214, name: "Dollar Rent a Car", domain: "dollar.com" },
      { id: 320, name: "Marriott", domain: "marriott.com.ar" },
      { id: 321, name: "Hyatt", domain: "hyatt.com" },
      { id: 322, name: "InterContinental (IHG)", domain: "ihg.com" },
      { id: 323, name: "Radisson", domain: "radisson.com.ar" },
      { id: 324, name: "Meliá", domain: "melia.com" },
      { id: 325, name: "Expedia", domain: "expedia.com.ar" },
      { id: 326, name: "Kayak", domain: "kayak.com.ar" },
      { id: 327, name: "TripAdvisor", domain: "tripadvisor.com.ar" },
      { id: 328, name: "Gol Linhas Aéreas", domain: "voegol.com.br" },
      { id: 329, name: "Copa Airlines", domain: "copaair.com" },
    ],
  },
  {
    id: "energia",
    name: "Energía",
    description: "Distribuidoras y empresas del sector energético",
    seoTopEntities: ["Edenor", "Camuzzi", "Metrogas"],
    seoIntro:
      "Logos de distribuidoras y empresas de energía en Argentina en PNG y SVG. Edenor, Camuzzi, Metrogas, Pampa Energía. Descarga gratis los logos de las principales empresas del sector energético.",
    entities: [
      { id: 211, name: "Edenor", domain: "edenor.com" },
      { id: 213, name: "Camuzzi Gas", domain: "camuzzigas.com" },
      { id: 214, name: "Metrogas", domain: "metrogas.com.ar" },
      { id: 215, name: "Pampa Energía", domain: "pampaenergia.com" },
    ],
  },
  {
    id: "indie-projects",
    name: "Indie Projects",
    description: "Proyectos independientes del ecosistema fintech argentino",
    seoTopEntities: ["Bond Terminal", "Dolarito", "Steamcito"],
    seoIntro:
      "Logos de proyectos independientes del ecosistema fintech argentino en PNG y SVG. Bond Terminal, Dolarito, Steamcito, ComparaTasas, Rendimientos, Impuestito y 3 más. Descarga gratis los logos de los principales indie projects de finanzas.",
    entities: [
      { id: 301, name: "ComparaTasas", domain: "comparatasas.ar" },
      { id: 302, name: "Rendimientos", domain: "rendimientos.co" },
      { id: 303, name: "Dolarito", domain: "www.dolarito.ar" },
      { id: 304, name: "Infleta", domain: "infleta.com.ar" },
      { id: 305, name: "Impuestito", domain: "www.impuestito.org" },
      { id: 306, name: "Bond Terminal", domain: "bondterminal.com" },
      { id: 307, name: "FinanzasArgy", domain: "finanzasargy.com" },
      { id: 308, name: "Steamcito", domain: "steamcito.com.ar" },
      { id: 309, name: "Gasti", domain: "gasti.pro" },
    ],
  },
]

export {
  getGoogleFaviconUrl,
  getDuckDuckGoFaviconUrl,
  getGoogleCurl,
  getDuckDuckGoCurl,
  type CurlConfig,
  defaultCurlConfig,
} from "./favicon-urls.ts"
